# Generated by Django 5.2.3 on 2025-07-16 17:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedPhoneUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, verbose_name='nome')),
                ('last_name', models.CharField(max_length=50, verbose_name='cognome')),
                ('pincode', models.CharField(max_length=10, verbose_name='pin')),
                ('serial_no', models.CharField(default='', max_length=24, verbose_name='matricola')),
                ('listening_enabled', models.BooleanField(default=False, verbose_name='ascolto')),
                ('recording_enabled', models.BooleanField(default=False, verbose_name='registrazione')),
                ('language', models.CharField(choices=[('it', 'Italiano'), ('en', 'Inglese'), ('fr', 'Francese'), ('de', 'Tedesco'), ('es', 'Spagnolo'), ('ar', 'Arabo')], max_length=4, verbose_name='lingua')),
                ('additional_calls', models.IntegerField(default=0, verbose_name='chiamate supplementari')),
                ('additional_due_date', models.DateTimeField(null=True, verbose_name='scadenza chiamate supplementari')),
                ('vipaccount', models.BooleanField(default=False, verbose_name='senza restizioni')),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='credito residuo')),
                ('four_bis_limited', models.BooleanField(default=False, verbose_name='4bis limitato')),
                ('archived_date', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'nuovo arrivo'), (1, 'in attesa di giudizio'), (2, 'definitivo')], default=0, verbose_name='stato')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('src', models.CharField(default='', max_length=80)),
                ('dst', models.CharField(default='', max_length=80)),
                ('calltype', models.IntegerField(default=0)),
                ('direction', models.IntegerField(default=1)),
                ('lawyer', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('pincode', models.CharField(default='', max_length=40)),
                ('uniqueid', models.CharField(default='', max_length=32)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('valid', models.BooleanField(default=True)),
                ('archived_phoneuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivedphoneuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ricarica')),
                ('recharge_date', models.DateTimeField()),
                ('reason', models.CharField(default='', max_length=255)),
                ('archived_phoneuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivedphoneuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('pincode', models.CharField(default='', max_length=10)),
                ('uniqueid', models.CharField(default='', max_length=32)),
                ('filename', models.CharField(default='', max_length=255)),
                ('archived_phoneuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivedphoneuser')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedWhitelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='etichetta')),
                ('phonenumber', models.CharField(max_length=40, verbose_name='telefono')),
                ('duration', models.IntegerField(verbose_name='durata massima')),
                ('kind', models.IntegerField(choices=[(0, 'Ordinaria'), (1, 'Primo ingresso')], default=0, verbose_name='tipologia')),
                ('lawyer', models.BooleanField(default=False, verbose_name='avvocato')),
                ('extraordinary', models.BooleanField(default=False, verbose_name='straordinaria')),
                ('real_mobile', models.BooleanField(default=False, verbose_name='cellulare')),
                ('archived_phoneuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archives.archivedphoneuser')),
            ],
        ),
    ]
