# Generated by Django 5.2.3 on 2025-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(default='', max_length=5)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=80, verbose_name='Direttrice')),
                ('prefix_list', models.TextField(verbose_name='Lista prefissi')),
                ('connection_charge', models.FloatField(verbose_name='Scatto alla risposta')),
                ('fee_per_second', models.FloatField(verbose_name='Tariffa al secondo')),
                ('reg_exp', models.TextField(verbose_name='Espressione regolare')),
                ('ordering', models.IntegerField(verbose_name='Ordinamento')),
                ('icon', models.CharField(default='zmdi zmdi-home', max_length=50)),
                ('position', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
    ]
