from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^phoneusers/$', phoneuser_home),
    url(r'^phoneusers/new/$', phoneuser_edit),
    url(r'^phoneusers/view/(?P<phoneuser_id>[0-9]*)$', phoneuser_view),
    url(r'^phoneusers/edit/$', phoneuser_edit),
    url(r'^phoneusers/save/$', phoneuser_save),
    url(r'^phoneusers/export/(?P<accountcode>[0-9]*)$', phoneuser_export),
    url(r'^phoneusers/name/(?P<accountcode>[0-9]*)$', phoneuser_name),
    url(r'^phoneusers/data/(?P<phoneuser_id>[0-9]*)$', phoneuser_data),
    #url(r'^phoneusers/enable/(?P<phoneuser_id>[0-9]*)$', phoneuser_enable),
    #url(r'^phoneusers/disable/(?P<phoneuser_id>[0-9]*)$', phoneuser_disable),
    url(r'^phoneusers/changestatus/$', phoneuser_change_status),
    url(r'^phoneusers/check/$', phoneuser_check_pincode),
    url(r'^phoneusers/ajax/$', phoneuser_ajax_view),
    url(r'^phoneusers/ajax/(?P<phoneuser_id>[0-9]*)$', phoneuser_ajax_view),
    url(r'^whitelist/ajax_list/(?P<phoneuser_id>[0-9]*)$',
     whitelist_items),
    url(r'^whitelist/edit/$',
     whitelist_edit),
    url(r'^whitelist/save/$',
     whitelist_save),
    url(r'^whitelist/remove/$',
     whitelist_remove),
    url(r'^whitelist/changestatus/$',
     whitelist_changestatus),
    url(r'^whitelist/changeordinary/$',
     whitelist_changeordinary),
    url(r'^whitelist/checkextra/$',
     whitelist_checkextra),                   
    url(r'^whitelist/edit/(?P<whitelist_id>[0-9]*)$',
     whitelist_edit),
    url(r'^whitelist/check/prefix/$',
     whitelist_check_prefix),
    url(r'^credit/new/$',
     credit_new),
    url(r'^credit/save/$',
     credit_save),
    url(r'^credit/ajax_list/(?P<phoneuser_id>[0-9]*)$',
     credit_items),
]
