# Generated by Django 5.2.3 on 2025-07-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField(verbose_name=datetime.datetime(2025, 7, 16, 17, 11, 42, 670295))),
                ('pincode', models.CharField(default='', max_length=10)),
                ('uniqueid', models.CharField(default='', max_length=32)),
                ('filename', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
