# Generated by Django 3.2.1 on 2025-07-16 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='calldate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 7, 16, 17, 50, 22, 376394)),
        ),
    ]