# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-07-11 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20161221_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='calldate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 7, 11, 16, 41, 55, 541374)),
        ),
    ]
