# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-06-12 19:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20220711_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='calldate',
            field=models.DateTimeField(verbose_name=datetime.datetime(2025, 6, 12, 19, 17, 17, 43012)),
        ),
    ]
