# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2022-07-11 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneusers', '0009_phoneuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneuser',
            name='covid_enabled',
            field=models.BooleanField(default=False, verbose_name=b'covid'),
        ),
    ]
