# Generated by Django 5.2.3 on 2025-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('what', models.TextField()),
                ('level', models.IntegerField(choices=[(0, 'info'), (1, 'warning'), (2, 'error')], default=0)),
                ('kind', models.IntegerField(choices=[(0, 'utente'), (1, 'numero autorizzato'), (2, 'credito')], default=0)),
            ],
        ),
    ]
