# Generated by Django 5.2.3 on 2025-07-16 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[(0, 'Anagrafica'), (1, 'Whitelist'), (2, 'Ricarica'), (3, 'Dettaglio'), (4, 'Registrazione')], max_length=1)),
                ('permission', models.CharField(choices=[(0, 'Nessuno'), (1, 'Lettura'), (3, 'Scrittura')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
