# Generated by Django 5.2.3 on 2025-07-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperbaCDR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calldate', models.DateTimeField()),
                ('src', models.CharField(default='', max_length=80)),
                ('dst', models.CharField(default='', max_length=80)),
                ('pincode', models.CharField(default='', max_length=40)),
                ('calltype', models.IntegerField(choices=[(0, 'ordinaria'), (1, 'straordinaria'), (2, 'speciale')], default=0)),
                ('direction', models.IntegerField(choices=[(0, 'interna'), (1, 'uscente'), (2, 'entrante')], default=1)),
                ('lawyer', models.BooleanField(default=False)),
                ('duration', models.IntegerField(default=0)),
                ('billsec', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('valid', models.BooleanField(default=True)),
                ('uniqueid', models.CharField(default='', max_length=32)),
            ],
            options={
                'db_table': 'superbacdr',
            },
        ),
    ]
